services:
  - type: web
    name: eventtix
    runtime: docker
    rootDir: eventtix
    dockerfilePath: ./Dockerfile
    startCommand: bash scripts/start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: FILESYSTEM_DISK
        value: local